stages:
  - build
  - benchmark

before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -

build:
  stage: build
  script:
    - make

# benchmark:skylake2x:barrelfishthroughput:
#   stage: benchmark
#   script:
#     - bash scripts/ci-barrelfish.bash throughput
#   dependencies:
#     - build
#   variables:
#     GIT_STRATEGY: fetch
#   tags:
#     - skylake2x

# benchmark:skylake2x:barrelfishlatency:
#   stage: benchmark
#   script:
#     - bash scripts/ci-barrelfish.bash latency
#   dependencies:
#     - build
#   variables:
#     GIT_STRATEGY: fetch
#   tags:
#     - skylake2x

benchmark:skylake2x:linuxlatency:
  stage: benchmark
  script:
    - bash scripts/ci-linux.bash latency
  dependencies:
    - build
  variables:
    GIT_STRATEGY: fetch
  tags:
    - skylake2x

benchmark:skylake2x:linuxthroughput:
  stage: benchmark
  script:
    - bash scripts/ci-linux.bash throughput
  dependencies:
    - build
  variables:
    GIT_STRATEGY: fetch
  tags:
    - skylake2x


# benchmark:skylake4x:barrelfishthroughput:
#   stage: benchmark
#   script:
#     - bash scripts/ci-barrelfish.bash throughput
#   dependencies:
#     - build
#   variables:
#     GIT_STRATEGY: fetch
#   tags:
#     - skylake4x

# benchmark:skylake4x:barrelfishlatency:
#   stage: benchmark
#   script:
#     - bash scripts/ci-barrelfish.bash latency
#   dependencies:
#     - build
#   variables:
#     GIT_STRATEGY: fetch
#   tags:
#     - skylake4x

benchmark:skylake4x:linuxlatency:
  stage: benchmark
  script:
    - bash scripts/ci-linux.bash latency
  dependencies:
    - build
  variables:
    GIT_STRATEGY: fetch
  tags:
    - skylake4x

benchmark:skylake4x:linuxthroughput:
  stage: benchmark
  script:
    - bash scripts/ci-linux.bash throughput
  dependencies:
    - build
  variables:
    GIT_STRATEGY: fetch
  tags:
    - skylake4x


