stages:
  - build
  - benchmark

build:
  stage: build
  script:
    - make

benchmark:
  stage: benchmark
  script:
    - bash scripts/ci.bash
  dependencies:
    - build
  variables:
    GIT_STRATEGY: none
