stages:
  - build
  - benchmark

before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -

build:
  stage: build
  script:
    - make

benchmark:skylake2x:
  stage: benchmark
  script:
    - bash scripts/ci.bash
  dependencies:
    - build
  variables:
    GIT_STRATEGY: none
  tags:
    - skylake2x

benchmark:skylake4x:
  stage: benchmark
  script:
    - bash scripts/ci.bash
  dependencies:
    - build
  variables:
    GIT_STRATEGY: none
  tags:
    - skylake4x

